[package]
name = "hellorust"
version = "0.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
json = "0.12.4"
mysql = "*"
dotenv = "*"
serde = { version = "1.0", features = ["derive"] }
reqwest = "*"
actix-files = "*"